// all 10 dgat mcp tool definitions + handlers
// each tool maps to one or more dgat rest api endpoints

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { DgatClient } from "./client.js";

export function registerTools(server: McpServer, client: DgatClient) {

  // 1. dgat_blueprint — get the full project architecture doc
  server.registerTool(
    "dgat_blueprint",
    {
      title: "DGAT Blueprint",
      description: "Get the project architecture blueprint — a synthesized overview of the entire codebase generated by analyzing all files and their relationships",
    },
    async () => {
      const blueprint = await client.getBlueprint();
      return {
        content: [{ type: "text", text: blueprint }],
      };
    }
  );

  // 2. dgat_file_context — the main tool agents will use before reading/editing any file
  server.registerTool(
    "dgat_file_context",
    {
      title: "DGAT File Context",
      description: "Get comprehensive context for a file: its purpose, what it imports, what depends on it, and how they relate. Use this before reading or editing any file to understand its role in the codebase.",
      inputSchema: {
        file: z.string().describe("Relative path of the file (e.g. src/auth/middleware.ts)"),
      },
    },
    async (args) => {
      const file = args.file;
      const ctx = await client.getContext(file);
      let text = `# ${ctx.name}\n\n`;
      text += `${ctx.description}\n\n`;
      text += `## Complexity\n`;
      text += `- Files that depend on this: ${ctx.complexity.incoming_deps}\n`;
      text += `- Files this depends on: ${ctx.complexity.outgoing_deps}\n`;
      text += `- Total transitive impact: ${ctx.complexity.transitive_dependents} files\n\n`;

      if (ctx.dependencies.length > 0) {
        text += `## Dependencies (what this file imports)\n`;
        for (const dep of ctx.dependencies) {
          text += `- \`${dep.file}\``;
          if (dep.description) text += ` — ${dep.description}`;
          text += `\n`;
        }
        text += "\n";
      }

      if (ctx.dependents.length > 0) {
        text += `## Dependents (files that use this)\n`;
        for (const dep of ctx.dependents) {
          text += `- \`${dep.file}\``;
          if (dep.description) text += ` — ${dep.description}`;
          text += `\n`;
        }
      }

      return { content: [{ type: "text", text }] };
    }
  );

  // 3. dgat_dependencies — what a file imports
  server.registerTool(
    "dgat_dependencies",
    {
      title: "DGAT Dependencies",
      description: "Get the list of files that a given file imports/depends on, with explanations of each relationship",
      inputSchema: {
        file: z.string().describe("Relative path of the file"),
      },
    },
    async (args) => {
      const file = args.file;
      const deps = await client.getDependencies(file);
      if (deps.length === 0) {
        return { content: [{ type: "text", text: `${file} has no tracked dependencies.` }] };
      }
      let text = `# Dependencies of \`${file}\`\n\n`;
      for (const dep of deps) {
        text += `- \`${dep.file}\``;
        if (dep.description) text += ` — ${dep.description}`;
        text += `\n`;
      }
      return { content: [{ type: "text", text }] };
    }
  );

  // 4. dgat_dependents — impact analysis before edits
  server.registerTool(
    "dgat_dependents",
    {
      title: "DGAT Dependents",
      description: "Get the list of files that depend on a given file. Use this for impact analysis before making changes — tells you what might break.",
      inputSchema: {
        file: z.string().describe("Relative path of the file"),
      },
    },
    async (args) => {
      const file = args.file;
      const deps = await client.getDependents(file);
      if (deps.length === 0) {
        return { content: [{ type: "text", text: `No files depend on \`${file}\`. Safe to modify without cascading effects.` }] };
      }
      let text = `# Files that depend on \`${file}\` (${deps.length})\n\n`;
      for (const dep of deps) {
        text += `- \`${dep.file}\``;
        if (dep.description) text += ` — ${dep.description}`;
        text += `\n`;
      }
      return { content: [{ type: "text", text }] };
    }
  );

  // 5. dgat_search — find files by name or description
  server.registerTool(
    "dgat_search",
    {
      title: "DGAT Search",
      description: "Search for files in the codebase by name or by their LLM-generated description content",
      inputSchema: {
        query: z.string().describe("Search query"),
        scope: z.enum(["name", "description", "both"]).optional().default("both").describe("Where to search: file names, descriptions, or both"),
      },
    },
    async (args) => {
      const query = args.query;
      const scope = args.scope || "both";
      const results = await client.search(query, scope);
      if (results.length === 0) {
        return { content: [{ type: "text", text: `No files found matching "${query}".` }] };
      }
      let text = `# Search results for "${query}" (${results.length} files)\n\n`;
      for (const r of results.slice(0, 20)) {
        text += `- \`${r.file}\` (${r.match_type})`;
        if (r.description) text += ` — ${r.description.slice(0, 120)}`;
        text += `\n`;
      }
      if (results.length > 20) {
        text += `\n... and ${results.length - 20} more results`;
      }
      return { content: [{ type: "text", text }] };
    }
  );

  // 6. dgat_impact_analysis — blast radius analysis
  server.registerTool(
    "dgat_impact_analysis",
    {
      title: "DGAT Impact Analysis",
      description: "Analyze the blast radius of changing a file — which other files would be affected, ranked by risk level (high/medium/low)",
      inputSchema: {
        file: z.string().describe("Relative path of the file to analyze"),
        change_type: z.enum(["modify", "delete", "rename"]).optional().default("modify").describe("Type of change planned"),
      },
    },
    async (args) => {
      const file = args.file;
      const change_type = args.change_type || "modify";
      const impact = await client.getImpact(file, change_type);
      let text = `# Impact Analysis: \`${file}\` (${change_type})\n\n`;
      text += `**${impact.summary}**\n\n`;

      if (impact.direct_dependents.length > 0) {
        text += `## High Risk (direct dependents)\n`;
        for (const d of impact.direct_dependents) {
          text += `- \`${d.file}\``;
          if (d.reason) text += ` — ${d.reason}`;
          text += `\n`;
        }
        text += "\n";
      }

      if (impact.transitive_dependents.length > 0) {
        text += `## Medium/Low Risk (transitive dependents)\n`;
        for (const d of impact.transitive_dependents.slice(0, 15)) {
          text += `- \`${d.file}\` (${d.risk})`;
          if (d.reason) text += ` — ${d.reason}`;
          text += `\n`;
        }
        if (impact.transitive_dependents.length > 15) {
          text += `\n... and ${impact.transitive_dependents.length - 15} more`;
        }
      }

      return { content: [{ type: "text", text }] };
    }
  );

  // 7. dgat_module_summary — directory-level overview
  server.registerTool(
    "dgat_module_summary",
    {
      title: "DGAT Module Summary",
      description: "Get a summary of a directory/module: all files it contains, internal dependencies, and how it connects to the rest of the codebase",
      inputSchema: {
        directory: z.string().describe("Relative path of the directory (e.g. src/auth/)"),
      },
    },
    async (args) => {
      const directory = args.directory;
      const summary = await client.getModuleSummary(directory);
      if (summary.error) {
        return { content: [{ type: "text", text: summary.error }] };
      }

      let text = `# Module: \`${directory}\`\n\n`;
      text += `- Files: ${summary.file_count}\n`;
      text += `- Internal dependencies: ${summary.internal_dep_count}\n`;
      text += `- External dependencies: ${summary.external_dep_count}\n`;
      text += `- External dependents: ${summary.depended_by_external_count}\n\n`;

      if (summary.files.length > 0) {
        text += `## Files\n`;
        for (const f of summary.files) {
          text += `- \`${f.file}\` — ${f.description || "(no description)"}\n`;
        }
        text += "\n";
      }

      if (summary.external_deps.length > 0) {
        text += `## External Dependencies\n`;
        for (const d of summary.external_deps.slice(0, 10)) {
          text += `- \`${d.from}\` → \`${d.to}\``;
          if (d.description) text += ` — ${d.description}`;
          text += `\n`;
        }
        text += "\n";
      }

      if (summary.depended_by_external.length > 0) {
        text += `## External Dependents (files outside this module that use it)\n`;
        for (const d of summary.depended_by_external.slice(0, 10)) {
          text += `- \`${d.from}\` → \`${d.to}\``;
          if (d.description) text += ` — ${d.description}`;
          text += `\n`;
        }
      }

      return { content: [{ type: "text", text }] };
    }
  );

  // 8. dgat_circular_deps — find circular imports
  server.registerTool(
    "dgat_circular_deps",
    {
      title: "DGAT Circular Dependencies",
      description: "Find circular dependency cycles in the codebase — files that import each other in a loop",
    },
    async () => {
      const result = await client.getCircularDeps();
      if (result.count === 0) {
        return { content: [{ type: "text", text: "No circular dependencies found." }] };
      }
      let text = `# Circular Dependencies (${result.count} cycles found)\n\n`;
      for (let i = 0; i < result.cycles.length; i++) {
        text += `## Cycle ${i + 1}\n`;
        text += result.cycles[i].map((f: string) => `\`${f}\``).join(" → ") + "\n\n";
      }
      return { content: [{ type: "text", text }] };
    }
  );

  // 9. dgat_entry_points — find root/entry files
  server.registerTool(
    "dgat_entry_points",
    {
      title: "DGAT Entry Points",
      description: "Find entry point files — files that many others depend on but have few dependencies themselves. These are likely main entry points, configuration, or core utilities.",
    },
    async () => {
      const entries = await client.getEntryPoints();
      if (entries.length === 0) {
        return { content: [{ type: "text", text: "No clear entry points found." }] };
      }
      let text = `# Entry Points (${entries.length} files)\n\n`;
      for (const e of entries) {
        text += `- \`${e.file}\` (used by ${e.depended_by_count} files, depends on ${e.depends_on_count})`;
        if (e.description) text += ` — ${e.description}`;
        text += `\n`;
      }
      return { content: [{ type: "text", text }] };
    }
  );

  // 10. dgat_scan — trigger a new scan or incremental update
  server.registerTool(
    "dgat_scan",
    {
      title: "DGAT Scan",
      description: "Trigger a new codebase scan (or incremental update) to refresh the dependency graph. Use this after making significant changes to the codebase.",
      inputSchema: {
        path: z.string().optional().describe("Path to scan (defaults to current workspace)"),
        incremental: z.boolean().optional().default(true).describe("Only re-scan changed files (much faster)"),
      },
    },
    async (args) => {
      const path = args.path;
      const incremental = args.incremental ?? true;
      const { exec } = await import("child_process");
      const { promisify } = await import("util");
      const execAsync = promisify(exec);

      const cmd = incremental ? "dgat update" : `dgat ${path || "."}`;
      try {
        const { stdout, stderr } = await execAsync(cmd, { timeout: 300000 });
        return {
          content: [
            { type: "text", text: `Scan complete.\n\n${stdout}${stderr}` },
          ],
        };
      } catch (err: unknown) {
        const msg = err instanceof Error ? err.message : String(err);
        return {
          content: [
            { type: "text", text: `Scan failed: ${msg}\n\nMake sure dgat is installed and in your PATH.` },
          ],
          isError: true,
        };
      }
    }
  );
}
